name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test README.md
      run: |
        gem install awesome_bot
        awesome_bot README.md
